AllCops:
  Exclude:
    - './config/boot.rb'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/posts_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/jobs/application_job.rb'
    - 'db/schema.rb'
    - 'config/puma.rb'
    - 'config/environments/production.rb'
    - 'spec/spec_helper.rb'
